# Generated by Django 4.1.7 on 2023-04-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_added',
            new_name='time',
        ),
    ]
