# Generated by Django 4.1.7 on 2023-04-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='В очереди', max_length=100),
        ),
    ]
